# Generated by Django 5.1.2 on 2024-10-16 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_due_date_task_due_time_task_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tag',
            new_name='tags',
        ),
    ]
